apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-atlas-system
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: mongodb-atlas-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: mongodb-atlas-system
spec:
  dnsNames:
    - timwatts.dev
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
